### PR TITLE
feat: add README.md and implement uninstall hooks in Plugin class

### PR DESCRIPTION
**Pull request by antonkovach**
### Summary

- **Added `README.md`**: Enhances project documentation by introducing a comprehensive `README.md` file, providing an overview, feature list, and usage examples.
- **Implemented uninstall hooks and methods in the `Plugin` class**: Facilitates proper removal of the plugin by registering uninstall hooks and providing methods to handle the uninstallation process, ensuring all related options and settings are cleanly removed.

### Changes

- **README.md**:
  - Added sections for project overview, features, and usage examples to guide developers in understanding and utilizing the plugin effectively.

- **src/Plugin.php**:
  - **Added `register_uninstall()` method**: Registers the necessary uninstall hooks for the plugin's removal.
  - **Implemented `uninstall($prefix)` static method**: Handles the uninstallation process by triggering the uninstall hook and cleaning up all options prefixed with the plugin identifier.
  - **Added `do_uninstall()` protected method**: Allows child classes to override and implement custom uninstallation logic for specific features.

### Notes

- The new `README.md` provides clear and comprehensive documentation, making it easier for developers to get started with and integrate the plugin into their projects.
- Implementing uninstall hooks ensures that the plugin can be removed gracefully, preventing leftover data and maintaining a clean WordPress environment.
- These enhancements improve the plugin’s maintainability, robustness, and user-friendliness, aligning with best practices in WordPress plugin development.

### CODE REVIEW

**Review by jtgraham38 — APPROVED** [review]
lgtm

**Comment by jtgraham38** [comment]
All these changes look quite good to me.  I am going to pout a different link to the article however.  Out of curiosity, why did you decide to contribute to this project?  Have you used this repo to develop your own plugin?  If you are interested in contributing further, i have some ideas for some good ways to further enhance the plugin that we could discuss!

**Comment by antonkovach** [comment]
I'm glad you like the changes!

I’m currently on sabbatical after spending 25 years as the CEO of a major development company. During this time, I’ve worked on several voluntary donation-related projects that rely on both our own and third-party WordPress plugins. Each plugin I’ve encountered has featured a completely unique style and code structure. After reviewing plugins of various sizes and complexities from across the globe, I was surprised by the lack of consistency—there wasn’t even a hint of similarity in their structures. This realization inspired me to explore a "Modern Approach to Plugin Development."

To address these challenges, I’ve been researching best practices, experimenting with different approaches, and seeking ways to better support developers.

Personally, I identify more as a "Chop" (Chat Oriented Programming) developer. My primary focus is on auditing and refining code rather than writing it entirely from scratch.

My current goal is to either discover or develop a modern plugin skeleton that embodies the principles I’ve outlined through my research:

---

### **Proposed Modern WordPress Plugin Development Manifesto for 2025**

#### **Core Principles**
1. **Value Stream-Based Feature Organization**  
   Features should be organized around value streams, aligning with user-centric outcomes and supporting an MVP strategy.

2. **Namespace and PSR-4 Standards**  
   Adopting modern PHP standards ensures clean, reusable, and conflict-free code.

3. **Sustainable Architecture**  
   For complex features, approaches like MVC+Service combined with Clean Code principles ensure clarity and long-term maintainability.

---

#### **Technical Practices**
4. **Hook-Based and Event-Driven Logic**  
   A flexible, WordPress-aligned approach ensures the plugin remains easily extensible.

5. **Dependency Injection (DI)**  
   Effectively managing dependencies results in modular, flexible, and testable code.

6. **Configuration-Driven Design (CDD)**  
   Prioritizing configuration-first logic allows for rapid customization and seamless adaptation to changing requirements.

---

#### **Quality, Automation, and User Experience**
7. **Chop-Compatible Documentation and Development Cycle**  
   APIs and documentation should prioritize clarity and be optimized for both developers and AI. This enables seamless code generation and supports efficient, iterative workflows in Chop-Compatible (Chat Oriented Programming) environments. Incorporating test-driven development (TDD) ensures robust, high-quality code.

8. **CI/CD Pipelines and Automated Testing**  
   Automating testing, building, and deployment minimizes errors, accelerates delivery, and ensures long-term stability through continuous monitoring.

9. **Localization (i18n)**  
   Built-in multilingual support makes plugins accessible to a global audience.

---

I’d greatly appreciate your feedback and any insights or experiences you could share. Thanks!

**Comment by jtgraham38** [comment]
I see, this makes sense.  Looks like an admirable project, and I think that WordPress definitely needs it.  I built this little framework mostly as an aid for myself in my projects.  Do you like this structure, and do you have any recommendations for improvements?  Thanks again for contributing!

**Pull request merged**
